services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    command:
      - -c
      - log_connections=true
      - -c
      - log_disconnections=true
      - -c
      - client_connection_check_interval=500
    ports:
      - 5432:5432
  nginx:
    image: nginx
    restart: always
    ports:
      - 5443:5443
    volumes:
      - ./nginx/cert.pem:/etc/ssl/certs/server.crt:ro
      - ./nginx/key.pem:/etc/ssl/certs/server.key:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

